export const ADD_COUNTRY_STATS = "ADD_COUNTRY_STATS";
export const REMOVE_COUNTRY_STATS = "REMOVE_COUNTRY_STATS";
export const UPDATE_COUNTRY_STATS = "UPDATE_COUNTRY_STATS";
export const GET_COUNTRIES_LIST = "GET_COUNTRIES_LIST";
export const APP_LOADING_STATE = "APP_LOADING_STATE";